# Generated by Django 4.1.3 on 2022-11-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=200, null=True)),
                ("prenom", models.CharField(max_length=200, null=True)),
                ("telephone", models.CharField(max_length=200, null=True)),
                ("bas", models.CharField(max_length=20, null=True)),
                ("longpan", models.CharField(max_length=20, null=True)),
                ("poignet", models.CharField(max_length=20, null=True)),
                ("longjupe", models.CharField(max_length=20, null=True)),
                ("genou", models.CharField(max_length=20, null=True)),
                ("cuiss", models.CharField(max_length=20, null=True)),
                ("bassin", models.CharField(max_length=20, null=True)),
                ("ceinture", models.CharField(max_length=20, null=True)),
                ("longchem", models.CharField(max_length=20, null=True)),
                ("frappe", models.CharField(max_length=20, null=True)),
                ("longrobe", models.CharField(max_length=20, null=True)),
                ("longcami", models.CharField(max_length=20, null=True)),
                ("pince", models.CharField(max_length=20, null=True)),
                ("tourtaille", models.CharField(max_length=20, null=True)),
                ("coole", models.CharField(max_length=20, null=True)),
                ("longtaille", models.CharField(max_length=20, null=True)),
                ("tourmanch", models.CharField(max_length=20, null=True)),
                ("longmanch", models.CharField(max_length=20, null=True)),
                ("poitrine", models.CharField(max_length=20, null=True)),
                ("dos", models.CharField(max_length=20, null=True)),
                ("epaul", models.CharField(max_length=20, null=True)),
                ("avcar", models.CharField(max_length=20, null=True)),
                ("arcar", models.CharField(max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_command", models.DateField()),
                ("transaction_id", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[("FINIS", "Finis"), ("EN COURS", "En cous")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelTenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.modeltenue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_livraison", models.DateField()),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comand_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.command",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Couturier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_cnib", models.CharField(max_length=100, null=True)),
                (
                    "specialite",
                    models.CharField(
                        choices=[("FEMME", "Femme"), ("HOMME", "Homme")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="command",
            name="couturier_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.couturier",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="ville_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.ville",
            ),
        ),
    ]
