# Generated by Django 4.1.3 on 2023-03-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, null=True)),
                ("prenom", models.CharField(max_length=200, null=True)),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Téléphone"
                    ),
                ),
                ("bas", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "longpan",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Longueur pantalon",
                    ),
                ),
                ("poignet", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "longjupe",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Longueur jupe",
                    ),
                ),
                ("genou", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cuiss",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Cuisse"
                    ),
                ),
                ("bassin", models.CharField(blank=True, max_length=20, null=True)),
                ("ceinture", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "longchem",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Longueur Chemise",
                    ),
                ),
                ("frappe", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "longrobe",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Longueur Robe",
                    ),
                ),
                (
                    "longcami",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Longueur Camisole",
                    ),
                ),
                ("pince", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tourtaille",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Tour de taille",
                    ),
                ),
                ("coole", models.CharField(blank=True, max_length=20, null=True)),
                ("longtaille", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tourmanch",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Tour de manche",
                    ),
                ),
                (
                    "longmanch",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Longueur manche",
                    ),
                ),
                ("poitrine", models.CharField(blank=True, max_length=20, null=True)),
                ("dos", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "epaul",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Epaule"
                    ),
                ),
                ("avcar", models.CharField(blank=True, max_length=20, null=True)),
                ("arcar", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="uploads_files/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_commande",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "adresse_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_commande", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="model_photo/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.modeltenue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_livraison",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("date_livaison", models.DateField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.command",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.tenue",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.command",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Couturier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, null=True)),
                ("prenom", models.CharField(max_length=100, null=True)),
                ("num_cnib", models.CharField(max_length=100, null=True)),
                (
                    "specialite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Femme", "Femme"),
                            ("Homme", "Homme"),
                            ("Mixte", "Mixte"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.post",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="command",
            name="articles",
            field=models.ManyToManyField(
                through="gestion.LigneCommande", to="gestion.tenue"
            ),
        ),
        migrations.AddField(
            model_name="command",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.client",
            ),
        ),
        migrations.AddField(
            model_name="command",
            name="couturier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.couturier",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.ville",
                verbose_name="Ville",
            ),
        ),
    ]
