# Generated by Django 4.1.3 on 2022-11-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="fichier",
            field=models.FileField(blank=True, null=True, upload_to="uploads_files/"),
        ),
    ]
