# Generated by Django 4.1.3 on 2022-11-13 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_client_fichier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="ville_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.ville",
                verbose_name="Ville",
            ),
        ),
    ]
