# Generated by Django 4.1.3 on 2022-11-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_alter_client_ville_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client", old_name="ville_id", new_name="ville",
        ),
    ]
