# Generated by Django 4.1.3 on 2022-11-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_rename_model_id_tenue_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="model_photo/"),
        ),
    ]
